/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Operacion;
import javax.swing.JOptionPane;
import Modelo.Operacion;

/**
 *
 * @author Gustavo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Operacion operacion;
    private int[][] matriz5x10;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Operacion op) {
        this.operacion=op;        
        this.matriz5x10=new int[5][10];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Punto1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btSumar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Punto2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        btCuadrado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Punto3 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btMetrosPulgadas = new javax.swing.JButton();
        btMetrosPies = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Punto4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        btHipotenusa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Punto5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        btFactorial = new javax.swing.JButton();
        Punto6 = new javax.swing.JPanel();
        btCargar10numeros = new javax.swing.JButton();
        Punto7 = new javax.swing.JPanel();
        btFormulaRara = new javax.swing.JButton();
        Punto8 = new javax.swing.JPanel();
        btCargarVector = new javax.swing.JButton();
        Punto9 = new javax.swing.JPanel();
        btMatrizIdentidad = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btSumFilasMatriz = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btCargarMatriz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabajo Práctico");

        Punto1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 1"));

        btSumar.setText("Sumar");
        btSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto1Layout = new javax.swing.GroupLayout(Punto1);
        Punto1.setLayout(Punto1Layout);
        Punto1Layout.setHorizontalGroup(
            Punto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSumar)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto1Layout.setVerticalGroup(
            Punto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Punto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Punto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Punto2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 2"));
        Punto2.setPreferredSize(new java.awt.Dimension(500, 81));

        btCuadrado.setText("x²");
        btCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto2Layout = new javax.swing.GroupLayout(Punto2);
        Punto2.setLayout(Punto2Layout);
        Punto2Layout.setHorizontalGroup(
            Punto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto2Layout.setVerticalGroup(
            Punto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Punto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btCuadrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        Punto3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 3"));
        Punto3.setPreferredSize(new java.awt.Dimension(500, 141));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("m → in");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("m → ft");

        btMetrosPulgadas.setText("Calcular");
        btMetrosPulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMetrosPulgadasActionPerformed(evt);
            }
        });

        btMetrosPies.setText("Calcular");
        btMetrosPies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMetrosPiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto3Layout = new javax.swing.GroupLayout(Punto3);
        Punto3.setLayout(Punto3Layout);
        Punto3Layout.setHorizontalGroup(
            Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Punto3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMetrosPulgadas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Punto3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMetrosPies)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        Punto3Layout.setVerticalGroup(
            Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto3Layout.createSequentialGroup()
                .addGroup(Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Punto3Layout.createSequentialGroup()
                        .addGroup(Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5)
                            .addComponent(btMetrosPulgadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Punto3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(Punto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMetrosPies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Punto4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 4"));
        Punto4.setToolTipText("");
        Punto4.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cateto Adyacente");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cateto Opuesto");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btHipotenusa.setText("Hipotenusa");
        btHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHipotenusaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto4Layout = new javax.swing.GroupLayout(Punto4);
        Punto4.setLayout(Punto4Layout);
        Punto4Layout.setHorizontalGroup(
            Punto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Punto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(Punto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Punto4Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btHipotenusa))
                    .addGroup(Punto4Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto4Layout.setVerticalGroup(
            Punto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Punto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHipotenusa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Punto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Punto5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 5"));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        btFactorial.setText("Factorial");
        btFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFactorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto5Layout = new javax.swing.GroupLayout(Punto5);
        Punto5.setLayout(Punto5Layout);
        Punto5Layout.setHorizontalGroup(
            Punto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Punto5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFactorial)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Punto5Layout.setVerticalGroup(
            Punto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Punto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFactorial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Punto6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 6"));

        btCargar10numeros.setText("Cargar números");
        btCargar10numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargar10numerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto6Layout = new javax.swing.GroupLayout(Punto6);
        Punto6.setLayout(Punto6Layout);
        Punto6Layout.setHorizontalGroup(
            Punto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCargar10numeros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto6Layout.setVerticalGroup(
            Punto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCargar10numeros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Punto7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 7"));

        btFormulaRara.setText("A[i+1] = ixA[i] + ix2 ~ A[1] = 1");
        btFormulaRara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFormulaRaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto7Layout = new javax.swing.GroupLayout(Punto7);
        Punto7.setLayout(Punto7Layout);
        Punto7Layout.setHorizontalGroup(
            Punto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFormulaRara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto7Layout.setVerticalGroup(
            Punto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFormulaRara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Punto8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 8"));

        btCargarVector.setText("Cargar vector");
        btCargarVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarVectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Punto8Layout = new javax.swing.GroupLayout(Punto8);
        Punto8.setLayout(Punto8Layout);
        Punto8Layout.setHorizontalGroup(
            Punto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCargarVector)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto8Layout.setVerticalGroup(
            Punto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCargarVector)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Punto9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 9"));

        btMatrizIdentidad.setText("Generar matriz identidad");
        btMatrizIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatrizIdentidadActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout Punto9Layout = new javax.swing.GroupLayout(Punto9);
        Punto9.setLayout(Punto9Layout);
        Punto9Layout.setHorizontalGroup(
            Punto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Punto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMatrizIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Punto9Layout.setVerticalGroup(
            Punto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Punto9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMatrizIdentidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Punto 10"));

        btSumFilasMatriz.setText("Sumar filas");
        btSumFilasMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumFilasMatrizActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        btCargarMatriz.setText("Generar matriz");
        btCargarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarMatrizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSumFilasMatriz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCargarMatriz)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSumFilasMatriz)
                    .addComponent(btCargarMatriz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Punto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Punto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Punto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Punto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Punto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Punto2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Punto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Punto3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Punto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Punto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Punto2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Punto3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Punto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Punto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Punto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Punto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Punto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Punto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumarActionPerformed
        
        try{
            double valor1=Double.valueOf(this.jTextField1.getText());
            double valor2=Double.valueOf(this.jTextField2.getText());
            double resultado;
            
            resultado=operacion.Suma(valor1, valor2);
            
            this.jLabel1.setText(String.valueOf(resultado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valores no válidos. Ingrese números.");
        }
    }//GEN-LAST:event_btSumarActionPerformed

    private void btMetrosPulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMetrosPulgadasActionPerformed
        try{
            double valor=Double.valueOf(this.jTextField5.getText());
            double resultado;
            
            resultado=operacion.metrosApulgadas(valor);
            
            this.jLabel8.setText(String.valueOf(resultado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido. Ingrese números.");
        }
    }//GEN-LAST:event_btMetrosPulgadasActionPerformed

    private void btMetrosPiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMetrosPiesActionPerformed
        try{
            double valor=Double.valueOf(this.jTextField4.getText());
            double resultado;
            
            resultado=operacion.metrosApies(valor);
            
            this.jLabel9.setText(String.valueOf(resultado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido. Ingrese números.");
        }
    }//GEN-LAST:event_btMetrosPiesActionPerformed

    private void btCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuadradoActionPerformed

        try{
            double valor=Double.valueOf(this.jTextField3.getText());
            double resultado;

            resultado=operacion.cuadrado(valor);

            this.jLabel4.setText(String.valueOf(resultado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido. Ingrese números.");
        }
    }//GEN-LAST:event_btCuadradoActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void btHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHipotenusaActionPerformed
        try{
            double catA=Double.valueOf(this.jTextField6.getText());
            double catO=Double.valueOf(this.jTextField7.getText());
            double resultado;
            
            resultado=operacion.hipotenusa(catA, catO);
            
            this.jLabel5.setText(String.valueOf(resultado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido. Ingrese números.");
        }
    }//GEN-LAST:event_btHipotenusaActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFactorialActionPerformed
        try{
            int valor=Integer.valueOf(this.jTextField8.getText());
            double resultado;
            
            if(valor<0){
                throw new Exception();
            }
            
            resultado=operacion.factorial(valor);
            
            this.jLabel10.setText(String.valueOf(resultado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe ingresar un número entero positivo.");
        }
    }//GEN-LAST:event_btFactorialActionPerformed

    private void btCargar10numerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargar10numerosActionPerformed
        int[] arEnteros=new int[10];
        String[] arString = new String[10];
        String salida="";
        
        try{
            for(int i=0;i<10;i++){
                arEnteros[i]=Integer.valueOf(JOptionPane.showInputDialog(i+1+" - "+"Ingrese un número."));
            }
            
            arString = operacion.prefijarCaracter(arEnteros, '0');
            
            for(int i:arEnteros){
                salida+=arString[i]+", ";
            }
            
            //se quitan los 2 ultimos caracteres
            salida=salida.substring(0,salida.length()-2);
            
            JOptionPane.showMessageDialog(null, "Los núneros ingresados fueron: "+salida);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido. Ingrese números.");
        }
        
    }//GEN-LAST:event_btCargar10numerosActionPerformed

    private void btFormulaRaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFormulaRaraActionPerformed
        int[] arreglo=new int[10];
        String salida="";
        
        operacion.generarVector(arreglo);
        
        for(int i:arreglo){
            salida+=i+" ";
        }
        
        JOptionPane.showMessageDialog(null,salida);
    }//GEN-LAST:event_btFormulaRaraActionPerformed

    private void btCargarVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarVectorActionPerformed
        int[] arreglo=new int[5];
        
        try{
            for(int i=0;i<arreglo.length;i++){
                arreglo[i]=Integer.valueOf(JOptionPane.showInputDialog(i+1+" - "+"Ingrese un número."));
            }
            
            if(operacion.posPrimerMenorCero(arreglo)==-1){
                JOptionPane.showMessageDialog(null, "El arreglo no tiene valores negativos.");
            }else{
                JOptionPane.showMessageDialog(null, "Posición del primer valor menor a 0 = "+operacion.posPrimerMenorCero(arreglo));
            }
            
            JOptionPane.showMessageDialog(null, "Valor máximo = "+operacion.valorMaximo(arreglo));
            JOptionPane.showMessageDialog(null, "Posición del valor máximo = "+operacion.posValorMaximo(arreglo));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido. Ingrese números.");
        }
    }//GEN-LAST:event_btCargarVectorActionPerformed

    private void btMatrizIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatrizIdentidadActionPerformed
        int[][] matriz=new int[10][10];
        String salida="";
        
        try{
            operacion.generarMatrizUnidad(matriz);
            
            for(int i=0;i<10;i++){
                for(int j=0;j<10;j++){
                    salida+=matriz[i][j];
                    salida+=" ";
                }
                salida+="\n";
            }
            
            this.jTextArea1.setText(salida);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btMatrizIdentidadActionPerformed

    private void btCargarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarMatrizActionPerformed
        String salida="";
        
        this.operacion.cargarMatriz(matriz5x10, 5, 10);
        
        for(int i=0;i<5;i++){
            for(int j=0;j<10;j++){
                salida+=matriz5x10[i][j];
                salida+=" ";
            }
            salida+="\n";
        }
        
        this.jTextArea2.setText(salida);
    }//GEN-LAST:event_btCargarMatrizActionPerformed

    private void btSumFilasMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumFilasMatrizActionPerformed
        int[] sumas=this.operacion.sumarFilasMatriz(matriz5x10, 5, 10);
        String salida="";
        
        for(int i:sumas){
            salida+=i;
            salida+=" ";
        }
        
        this.jTextArea2.append("\n"+salida);
    }//GEN-LAST:event_btSumFilasMatrizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Operacion op=new Operacion();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(op).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Punto1;
    private javax.swing.JPanel Punto2;
    private javax.swing.JPanel Punto3;
    private javax.swing.JPanel Punto4;
    private javax.swing.JPanel Punto5;
    private javax.swing.JPanel Punto6;
    private javax.swing.JPanel Punto7;
    private javax.swing.JPanel Punto8;
    private javax.swing.JPanel Punto9;
    private javax.swing.JButton btCargar10numeros;
    private javax.swing.JButton btCargarMatriz;
    private javax.swing.JButton btCargarVector;
    private javax.swing.JButton btCuadrado;
    private javax.swing.JButton btFactorial;
    private javax.swing.JButton btFormulaRara;
    private javax.swing.JButton btHipotenusa;
    private javax.swing.JToggleButton btMatrizIdentidad;
    private javax.swing.JButton btMetrosPies;
    private javax.swing.JButton btMetrosPulgadas;
    private javax.swing.JToggleButton btSumFilasMatriz;
    private javax.swing.JButton btSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
